export const BILLING_MINE_LIST_REQUEST = 'BILLING_MINE_LIST_REQUEST';
export const BILLING_MINE_LIST_SUCCESS = 'BILLING_MINE_LIST_SUCCESS';
export const BILLING_MINE_LIST_FAIL = 'BILLING_MINE_LIST_FAIL';
